#include <vector>
using namespace std;

void print_square(int N, double* S);
void print_square_ss(int N, double* S);
void trans(double* Bt, double* B, int m, int n);
int Diagonalize(double* A, double* eigen, int size);
int Invert(double* A, int m);
int mat_root(double* A, int size);
int mat_root_inv(double* A, int size);
int mat_times_mat(double* C, double* A, double* B, int M, int N, int K);
int mat_times_mat(double* C, double* A, double* B, int size);
int mat_times_mat_at(double* C, double* A, double* B, int size);
int mat_times_mat_bt(double* C, double* A, double* B, int M, int N, int K);
int mat_times_mat_bt(double* C, double* A, double* B, int size);
int mat_times_mat_at_bt(double* C, double* A, double* B, int size);
double Inr_1s(double zeta, double r);
double Inr_2s(double zeta, double r);
double Inr_2p(double zeta, double r);
double Inr_3s(double zeta, double r);
double Inr_3p(double zeta, double r);
double Inr_3d(double zeta, double r);
double Inr_4f(double zeta, double r);
int fact(int N);
double norm_sh(int l, int m);
double norm_sv(int n, int l, int m, double zeta);
double norm(int n, int l, int m, double zeta);
double sh_1c(int l, int m, double x, double y, double z, double r);
double sh_2c(int l2, int m2, int l3, int m3, double x2, double y2, double z2, double x3, double y3, double z3, double r2, double r3);
double slater_1s_ns(const double* k, size_t dim, void* params);
double slater_2s_ns(const double* k, size_t dim, void* params);
double slater_2p_ns(const double* k, size_t dim, void* params);
double slater_3s_ns(const double* k, size_t dim, void* params);
double slater_3p_ns(const double* k, size_t dim, void* params);
double slater_3d_ns(const double* k, size_t dim, void* params);
double slater_4f_ns(const double* k, size_t dim, void* params);
double slater_1s_ns_ns(const double* k, size_t dim, void* params);
double slater_2s_ns_ns(const double* k, size_t dim, void* params);
double slater_2p_ns_ns(const double* k, size_t dim, void* params);
double slater_3d_ns_ns(const double* k, size_t dim, void* params);
double ne1(const double* k, size_t dim, void* params);
double overlap1(const double* k, size_t dim, void* params);
double ke1(const double* k, size_t dim, void* params);
int ke_op(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int ne_op(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int overlap_op(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_2c_1s(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_2c_2s(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_2c_2p(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_2c_3s(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_2c_3p(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_2c_3d(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_2c_4f(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_3c_1s(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_3c_2s(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_3c_2p(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_3c_3s(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_3c_3p(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
int slater_3c_3d(unsigned dim, const double* x, void* data, unsigned fdim, double* retval);
void display_results (char *title, double result, double error);
void integrate_2c(int type, int integrand_fdim, double* par, int dim, double* xl, double* xu, int maxEval, double tol, double& val, double& err);
void integrate_3c(int type, int integrand_fdim, double* par, int dim, double* xl, double* xu, int maxEval, double tol, double& val, double& err);
void integrate(int type, int integrand_fdim, double* par, int dim, double* xl, double* xu, int maxEval, double tol, double& val, double& err);
void ao_to_mo(int N, double* jAO, double* jMO, double* jCA, double* tmp);
void mo_coeff_to_pao(int No, int N, double* jCA, double* Pao);
double get_ehf(int No, int N, double* Pao, double* jHc, double* Fao);
void get_G(int N, double* Pao, double* g, double* G);
double hartree_fock(int No, int N, double* S, double* T, double* En, double* g);
double nuclear_repulsion(int natoms, double* coords);
void get_sign_xyz(int l, int m, int &ox, int &oy, int &oz);
int check_2c_spherical(double x1, double x2, int l1, int l2, int m1, int m2);
int zero_check_3c(int n1, int l1, int m1, int n2, int l2, int m2, int n3, int l3, int m3, double x1, double x2, double x3);
void compute_integrals(vector<vector<double> > basis, vector<vector<double> > basis_aux, double* coords, double* xl, double* xu, double* S, double* T, double* En, double* g, double tol);
void add_p(vector<vector<double> > &basis_aux, vector<double> ao1, double zeta);
